---
title: "Remesas"
author: "CAAS"
date: "19 de agosto de 2018"
output:
  html_document:
    df_print: paged
    highlight: tango
    theme: lumen
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## {.tabset .tabset-fade .tabset-pills}

```{r echo=FALSE , results='hide', message=FALSE , warning=FALSE}

#Aquí cargo las librerías necesarias y la que tal vez tomé más trabajo instalar es la de "mxmaps", para más información sobre la misma recomiendo buscarla por separado.

library(tidyr)
library(knitr)
library(plotly)
library(ggplot2)
library(haven)
library(dplyr)
library(readxl)
library(rgdal)
library(readr)
library(mxmaps)
library(data.table)

```

```{r echo=FALSE , results='hide', message=FALSE , warning=FALSE}
# Aquí se cargan las bases de datos


#Primero creamos el data fram de las remesas.

datos <- read_csv("Remesas por entidad.csv")

id <- c("Fecha", "01", "02", "03", "04", "05", "06", "07", "08", "09", 10:32, "Total")

names(datos) <- id

datos <- melt(datos, id.vars = "Fecha", measure.vars = id[2:34] )

datos_2003 <- filter(datos, Fecha %in% c("01/01/2003"))

datos_2003 <- datos_2003[1:32,]

datos_2018 <- filter(datos, Fecha %in% c("01/01/2018"))

datos_2018 <- datos_2018[1:32,]

#Este data frame está alojado en la librería de mxmaps
df <- df_mxstate

datos_mapa<-data.frame("id" = df$region, "Estados" = df$state_name, "Abrev." = df$state_abbr,
                       "2003" = datos_2003$value, "2018" = datos_2018$value)

datos_mapa$X2003 <- round(datos_mapa$X2003, 1)

datos_mapa$X2018 <- round(datos_mapa$X2018, 1)

#En esta parte se carga el marco geoestadístico, en donde está el pnto se pone la dirección de donde se encuentra el  archivo .shp y en layer se pone el nombre que en este caso es ESTADOS, para evitar estar cambiando los directorios recomiendo dejarlo tal cual y poner el RMD junto con los archivos del marco estadístico

capa_estados <-readOGR(".", layer="ESTADOS")

#Aquí convertimos el shapefile en un data frame

estados <- fortify(capa_estados, region="CVE_ENT")

#Se combinan los data frames para poder mapearlos

remesas_ent <- inner_join(estados, datos_mapa, by="id")

#Formato para que se vea bonito que encontré en algún articulo que no recuerdo

theme_clean <- function(base_size = 12) {
    require(grid)
    theme_grey(base_size) %+replace%
            theme(
                    axis.title = element_blank(),
                    axis.text = element_blank(),
                    panel.background = element_blank(),
                    panel.grid = element_blank(),
                    axis.ticks.length = unit(0,"cm"), 
                    axis.ticks.margin = unit(0,"cm"),
                    panel.margin = unit(0,"lines"),
                    plot.margin = unit(c(0, 0, 0, 0), "lines"),
                    complete = TRUE
            )}


```

```{r echo=FALSE , message=FALSE , warning=FALSE}

ggplotly(ggplot(remesas_ent, aes(text = paste(remesas_ent$Estados, ":" ,
                                              remesas_ent$X2003, "mill. de dls."))) +  
  geom_polygon(aes(x=long, y=lat, group=group, fill=remesas_ent$X2003),  
               color="white") +
  scale_fill_distiller(type = "seq", palette = 'Greens', direction = 1, aesthetics = "fill"
                       , name = "Remesas en 2003") +
  theme_clean(), tooltip = c("text")) %>%
layout(legend = list(orientation = 'h'),
       autosize = F, width = 900, height = 700)

```
